DEFAULT_REDIS_HOST = 'localhost'

DEFAULT_REDIS_PORT = 6379

DEFAULT_REDIS_PASSWORD = None

REDIS_DB_QUESTIONS = 0

REDIS_DB_USERS = 1

DEFAULT_ANSWER_RATIO_BORDER = 0.9

NEW_QUESTION_BUTTON = 'Новый вопрос'

GIVE_UP_BUTTON = 'Сдаться'

SCORES_BUTTON = 'Мой счет'
